name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 17.1.1
          branches: |
            [
              'master'
            ]
        env:
          GITHUB_TOKEN: ${{ github.token }}
